# Maps configuration file
# Defines three maps with different parameters

maps:
  map1:
    name: "high_resolution_map"
    resolution: 0.05  # 5cm per cell
    width: 20.0       # 20 meters
    height: 15.0      # 15 meters
    origin: [0.0, 0.0, 0.0]  # [x, y, theta] in meters and radians
    
  map2:
    name: "medium_resolution_map"
    resolution: 0.1   # 10cm per cell
    width: 30.0       # 30 meters
    height: 20.0      # 20 meters
    origin: [25.0, 0.0, 0.0]  # Offset to the right
    
  map3:
    name: "low_resolution_map"
    resolution: 0.2   # 20cm per cell
    width: 40.0       # 40 meters
    height: 25.0      # 25 meters
    origin: [0.0, 20.0, 0.0]  # Offset upward
